### ISSUE TITLE
Trying to Login to Dashboard throws error "Unknown column 'accounts.email' in 'field list'"

### ISSUE THREAD

**Issue by justwlocke** [DarkflameUniverse/NexusDashboard#71]
~~Am I dumb? Did I miss a step somewhere?~~

~~I went through the whole install process via the "Windows Manual" steps, ran the page with "flask run", I've got it open in my browser. But I need to sign in with a username and password, and I never made one for Nexus. (And there's no register button anywhere, despite me thinking there should be one while looking at the files)~~

I filled out settings.py with the username/pass for the database, and I tried them on the login page, but it throws an error, simply saying 
"Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

Yet the server itself doesn't show an error in powershell.
The only error I wasn't able to fix was the command "flask db upgrade" not being able to find the brickprimatives folder in \res\ (Which it couldn't find because **I** couldn't find it to put it in there.)((I assume the same would happen with the models textures and ui folders, as I couldn't find those either.))

Windows 10
With Python 3.8.0, as specified in the setup
ImageMagick-7.1.1-Q16

**Comment by aronwk-aaron** [comment]
- enabling registration is a setting
- It uses the game's DB, the same DB that you have the game server connected to, so the same credentials that you would use to log into the game.
Also make sure it's connected to the same db as the game server
- If the command line isn't outputting any errors when run, then I can't really help with the internal server error. Need error logs from the application in order to diagnose issues.

Please ensure that you've read the setup step carefully and check all the settings under `app/settings_example.py` for what you can customize

**Comment by aronwk-aaron** [comment]
you need to run migrations

**Comment by justwlocke** [comment]
Ah... I could have sworn I ran both previously, but upon redoing it, its fixed the issue.
I must've missed "flask db upgrade", or maybe something broke it.

Either way, I've logged in now. Thank you.
